apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.appReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.appImage }}:{{ .Values.appVersion }}"
          ports:
          - containerPort: {{ .Values.containerPort }}
          env:
          {{- range .Values.containerEnvVars}}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- end}}
          #- name: PRODUCT_CATALOG_SERVICE_ADDR
          #  value: "productcatalogservice:3550"
          #- name: CURRENCY_SERVICE_ADDR
          #  value: "currencyservice:7000"
          #- name: CART_SERVICE_ADDR
          #  value: "cartservice:7070"
          #- name: RECOMMENDATION_SERVICE_ADDR
          #  value: "recommendationservice:8080"
          #- name: SHIPPING_SERVICE_ADDR
          #  value: "shippingservice:50051"
          #- name: CHECKOUT_SERVICE_ADDR
          #  value: "checkoutservice:5050"
          #- name: AD_SERVICE_ADDR
          #  value: "adservice:9555"